### ISSUE TITLE
Bug in `tzByLabel` that flips sign of timezones (GMT+4 becomes GMT-4)

### ISSUE THREAD

**Issue by TheOddler** [ysangkok/haskell-tz#2]
I encountered some strange behaviour, when I do the following:

```
print $ tzByLabel <$> fromTZName "Etc/GMT-4"
```

It shows as output:

```
Just (TZ {_tzTrans = [-9223372036854775808], _tzDiffs = [14400], _tzInfos = [(False,"+04")]})
```

As you can see, it shows `+04` as the timezone, whereas the string I started with had `-4` in it.

I'm still looking into why exactly, but I found the following lead so far:

The source for `tzDescriptions` ([link](https://hackage.haskell.org/package/tzdata-0.2.20221011.0/docs/src/Data.Time.Zones.DB.html#tzDescriptions)) has an element for GMT-4 as: `p "Etc/GMT-4" Etc__GMT_4 "TZif2\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\EOT\NUL\NUL8@\NUL\NUL+04\NULTZif2\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\EOT\NUL\NUL8@\NUL\NUL+04\NUL\n<+04>-4\n"`

Notice multiple occurrences of `+04` in that last string, whereas the first string shows `GTM-4`. Maybe there's a mismatch in that data?

**Comment by puellanivis** [comment]
The meaning of `GMT-4` isn’t `localtime = GMT - 4` but rather `localtime - 4 = GMT`. The tzDescription matches that supplied by the IANA for that timezone. 🙃

**Comment by TheOddler** [comment]
That is super confusing, but does explain it. Thank you so much!
